<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://cm.charter.com/Enterprise/Order/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://cm.charter.com/Enterprise/Invoice/V1" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/Test1221App/ValidateOrderProcess/ValidateOrderProcess"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/Test1221App/CalculateInvoiceProcess/CalculateInvoiceProcess">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ValidateOrderProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OrderRequest" namespace="http://cm.charter.com/Enterprise/Order/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://soalt03.flexagon:8001/soa-infra/services/default/CalculateInvoiceProcess!1.0/WSDLs/CalculateInvoiceProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InvoiceRequest" namespace="http://cm.charter.com/Enterprise/Invoice/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE AUG 28 20:23:06 CDT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InvoiceRequest>
         <tns:Account>
            <xsl:value-of select="/ns0:OrderRequest/ns0:Order/ns0:Account"/>
         </tns:Account>
         <tns:Number>
            <xsl:value-of select="/ns0:OrderRequest/ns0:Order/ns0:Number"/>
         </tns:Number>
         <tns:Quantity>
            <xsl:value-of select="/ns0:OrderRequest/ns0:Order/ns0:Quantity"/>
         </tns:Quantity>
         <tns:Price/>
      </tns:InvoiceRequest>
   </xsl:template>
</xsl:stylesheet>
